PYTHON CODE

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import matplotlib
matplotlib.rcParams

RcParams({'_internal.classic_mode': False,
          'agg.path.chunksize': 0,
          'animation.bitrate': -1,
          'animation.codec': 'h264',
          'animation.convert_args': ['-layers', 'OptimizePlus'],
          'animation.convert_path': 'convert',
          'animation.embed_limit': 20.0,
          'animation.ffmpeg_args': [],
          'animation.ffmpeg_path': 'ffmpeg',
          'animation.frame_format': 'png',
          'animation.html': 'none',
          'animation.writer': 'ffmpeg',
          'axes.autolimit_mode': 'data',
          'axes.axisbelow': 'line',
          'axes.edgecolor': 'black',
          'axes.facecolor': 'white',
          'axes.formatter.limits': [-5, 6],
          'axes.formatter.min_exponent': 0,
          'axes.formatter.offset_threshold': 4,
          'axes.formatter.use_locale': False,
          'axes.formatter.use_mathtext': False,
          'axes.formatter.useoffset': True,
          'axes.grid': False,
          'axes.grid.axis': 'both',
   

In [4]:
df = pd.read_csv("C:\\Users\\aditi\\OneDrive\\Desktop\\UG PROJECT\\MODEL\\dams_lifetime.csv")
df.head()

Algeria  pg    42    1884  1885    2
0    Algeria  pg  43.0  1871.0  1881  4.0
1    Algeria  pg  43.0  1885.0  1927  4.0
2    Algeria  pg   2.0  1858.0  1885  4.0
3    Algeria  te  27.0  1861.0  1862  3.0
4  Argentina  er  17.7  1938.0  1970  4.0

In [5]:
df.shape

(168, 6)

DATA CLEANING

In [6]:
df.groupby('Country')['Country'].agg('count')

KeyError: 'Country'

In [ ]:
df1 = df.drop('Type', axis='columns')
df1.head()

Country     H  constuction_year  failure_year  Age 
0  Algeria  42.0            1884.0          1885   2.0
1  Algeria  43.0            1871.0          1881   4.0
2  Algeria  43.0            1885.0          1927   4.0
3  Algeria   2.0            1858.0          1885   4.0
4  Algeria  27.0            1861.0          1862   3.0

In [ ]:
df1.isnull().sum()

Country             0
H                   5
constuction_year    7
failure_year        0
Age                 3
dtype: int64

In [ ]:
df1.H = df1.H.fillna(df1.H.mean())
df1.H.isnull().sum()

0

In [ ]:
df2 = df1.dropna()
df2.isnull().sum()

Country             0
H                   0
constuction_year    0
failure_year        0
Age                 0
dtype: int64

In [ ]:
df2['Age '].unique()

array([2., 4., 3., 1.])

In [ ]:
df2.head()


Country     H  constuction_year  failure_year  Age 
0  Algeria  42.0            1884.0          1885   2.0
1  Algeria  43.0            1871.0          1881   4.0
2  Algeria  43.0            1885.0          1927   4.0
3  Algeria   2.0            1858.0          1885   4.0
4  Algeria  27.0            1861.0          1862   3.0

MACHINE LEARNING

In [ ]:
dummies = pd.get_dummies(df2.Country)
dummies = dummies.astype(int)
dummies

Algeria  Argentina  Australia  Brazil  Canada  Chile  China  \
0          1          0          0       0       0      0      0   
1          1          0          0       0       0      0      0   
2          1          0          0       0       0      0      0   
3          1          0          0       0       0      0      0   
4          1          0          0       0       0      0      0   
..       ...        ...        ...     ...     ...    ...    ...   
164        0          0          0       0       0      0      0   
165        0          0          0       0       0      0      0   
166        0          0          0       0       0      0      0   
167        0          0          0       0       0      0      0   
168        0          0          0       0       0      0      0   

     Czechoslovakia  France  Great Britain  ...  Pakistan  Romania  \
0                 0       0              0  ...         0        0   
1                 0       0              0  ...         0        0   
2                 0       0              0  ...         0        0   
3                 0       0              0  ...         0        0   
4                 0       0              0  ...         0        0   
..              ...     ...            ...  ...       ...      ...   
164               0       0              0  ...         0        0   
165               0       0              0  ...         0        0   
166               0       0              0  ...         0        0   
167               0       0              0  ...         0        0   
168               0       0              0  ...         0        0   

     South Africa  Spain  Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0               0      0          0       0       0    0     0           0  
1               0      0          0       0       0    0     0           0  
2               0      0          0       0       0    0     0           0  
3               0      0          0       0       0    0     0           0  
4               0      0          0       0       0    0     0           0  
..            ...    ...        ...     ...     ...  ...   ...         ...  
164             0      0          0       0       0    1     0           0  
165             0      0          0       0       0    0     1           0  
166             0      0          0       0       0    0     1           0  
167             0      0          0       0       0    0     0           1  
168             0      0          0       0       0    0     0           1  

[161 rows x 29 columns]

In [ ]:
df3 = pd.concat([df2, dummies], axis='columns')
df3.head()

Country     H  constuction_year  failure_year  Age   Algeria  Argentina  \
0  Algeria  42.0            1884.0          1885   2.0        1          0   
1  Algeria  43.0            1871.0          1881   4.0        1          0   
2  Algeria  43.0            1885.0          1927   4.0        1          0   
3  Algeria   2.0            1858.0          1885   4.0        1          0   
4  Algeria  27.0            1861.0          1862   3.0        1          0   

   Australia  Brazil  Canada  ...  Pakistan  Romania  South Africa  Spain  \
0          0       0       0  ...         0        0             0      0   
1          0       0       0  ...         0        0             0      0   
2          0       0       0  ...         0        0             0      0   
3          0       0       0  ...         0        0             0      0   
4          0       0       0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 34 columns]

In [ ]:
df4 = df3.drop('Country', axis='columns')
df4.head()

H  constuction_year  failure_year  Age   Algeria  Argentina  Australia  \
0  42.0            1884.0          1885   2.0        1          0          0   
1  43.0            1871.0          1881   4.0        1          0          0   
2  43.0            1885.0          1927   4.0        1          0          0   
3   2.0            1858.0          1885   4.0        1          0          0   
4  27.0            1861.0          1862   3.0        1          0          0   

   Brazil  Canada  Chile  ...  Pakistan  Romania  South Africa  Spain  \
0       0       0      0  ...         0        0             0      0   
1       0       0      0  ...         0        0             0      0   
2       0       0      0  ...         0        0             0      0   
3       0       0      0  ...         0        0             0      0   
4       0       0      0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 33 columns]

In [ ]:
df4.shape

(161, 33)

In [ ]:
x = df4.drop(['failure_year','Age '], axis='columns')
y1 = df4[['failure_year']]
y2 = df4[['Age ']]

In [ ]:
x.head()

H  constuction_year  Algeria  Argentina  Australia  Brazil  Canada  \
0  42.0            1884.0        1          0          0       0       0   
1  43.0            1871.0        1          0          0       0       0   
2  43.0            1885.0        1          0          0       0       0   
3   2.0            1858.0        1          0          0       0       0   
4  27.0            1861.0        1          0          0       0       0   

   Chile  China  Czechoslovakia  ...  Pakistan  Romania  South Africa  Spain  \
0      0      0               0  ...         0        0             0      0   
1      0      0               0  ...         0        0             0      0   
2      0      0               0  ...         0        0             0      0   
3      0      0               0  ...         0        0             0      0   
4      0      0               0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 31 columns]

In [ ]:
y1.head()

failure_year
0          1885
1          1881
2          1927
3          1885
4          1862

In [ ]:
y2.head()

Age 
0   2.0
1   4.0
2   4.0
3   4.0
4   3.0

In [ ]:
y = pd.concat([y1, y2], axis=1)

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=42)

In [ ]:
regressor = MultiOutputRegressor(RandomForestRegressor(random_state=42))

In [ ]:
regressor.fit(x_train, y_train)

MultiOutputRegressor(estimator=RandomForestRegressor(random_state=42))

In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
y_pred_failure_year = y_pred[:,0]
y_pred_age = y_pred[:, 1]

In [ ]:
y_pred_failure_year

array([1981.09, 1931.74, 1915.61, 1981.62, 1927.07, 1956.17, 1937.99,
       1951.94, 1905.36, 1978.67, 1947.55, 1977.6 , 1894.01, 1962.73,
       1964.62, 1977.5 , 1951.28, 1937.3 , 1979.22, 1858.44, 1956.13,
       1973.35, 1976.18, 1966.33, 1941.51, 1960.59, 1874.63, 1834.48,
       1978.1 , 1976.26, 1956.96, 1940.45, 1930.88, 1894.17, 1911.51,
       1928.03, 1927.69, 1955.51, 1918.76, 1972.13, 1939.36, 1905.79])

In [ ]:
y_pred_age

array([2.97, 2.94, 3.15, 2.75, 2.71, 3.6 , 3.18, 2.54, 2.43, 2.82, 2.7 ,
       1.87, 3.79, 2.63, 2.97, 2.84, 2.66, 3.3 , 2.57, 3.26, 3.57, 2.3 ,
       2.24, 3.35, 3.7 , 2.53, 3.39, 2.99, 2.5 , 3.31, 3.14, 3.34, 3.36,
       2.06, 3.51, 2.5 , 3.23, 3.8 , 2.81, 2.81, 2.99, 3.65])

In [ ]:
print("Predicted 'failure_year' values:")
print(y_pred_failure_year)
print("\nPredicted 'Age ' values:")
print(y_pred_age)

Predicted 'failure_year' values:
[1981.09 1931.74 1915.61 1981.62 1927.07 1956.17 1937.99 1951.94 1905.36
 1978.67 1947.55 1977.6  1894.01 1962.73 1964.62 1977.5  1951.28 1937.3
 1979.22 1858.44 1956.13 1973.35 1976.18 1966.33 1941.51 1960.59 1874.63
 1834.48 1978.1  1976.26 1956.96 1940.45 1930.88 1894.17 1911.51 1928.03
 1927.69 1955.51 1918.76 1972.13 1939.36 1905.79]

Predicted 'Age ' values:
[2.97 2.94 3.15 2.75 2.71 3.6  3.18 2.54 2.43 2.82 2.7  1.87 3.79 2.63
 2.97 2.84 2.66 3.3  2.57 3.26 3.57 2.3  2.24 3.35 3.7  2.53 3.39 2.99
 2.5  3.31 3.14 3.34 3.36 2.06 3.51 2.5  3.23 3.8  2.81 2.81 2.99 3.65]


In [ ]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(x_train, y_train)
lr_clf.score(x_test, y_test)

0.2362540135800889

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), x, y, cv=cv)

array([ 9.85535458e-02,  1.22846606e-01,  1.67368119e-02, -2.35871504e+20,
       -3.49607588e-01])

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor



c:\Users\Ayush\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\optimize\_nnls.py:135: LinAlgWarning: Ill-conditioned matrix (rcond=3.98515e-21): result may not be accurate.
  s[P] = solve(AtA[P_ind[:, None], P_ind[None, :]], Atb[P],


RuntimeError: Maximum number of iterations reached.

In [ ]:
def predict(Country,H	,constuction_year):
    Con_index = np.where(x.columns==Country)[0][0]
    x_input = np.zeros(len(x.columns))
    x_input[0] = H
    x_input[1] = constuction_year

    if Con_index >=0:
        x_input[Con_index] = 1
    return lr_clf.predict([x_input])[0]

In [ ]:
predict('India',43,1945)

C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1953.08555526,    2.50396188])

MODEL EXPORTING

In [ ]:
import pickle
with open('dam_failure_model.pickle', 'wb') as f:
    pickle.dump(lr_clf,f)

In [ ]:
import json
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open ('columns.json', 'w') as f:
    f.write(json.dumps(columns))