PYTHON CODE

In [134]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import matplotlib
matplotlib.rcParams

RcParams({'_internal.classic_mode': False,
          'agg.path.chunksize': 0,
          'animation.bitrate': -1,
          'animation.codec': 'h264',
          'animation.convert_args': ['-layers', 'OptimizePlus'],
          'animation.convert_path': 'convert',
          'animation.embed_limit': 20.0,
          'animation.ffmpeg_args': [],
          'animation.ffmpeg_path': 'ffmpeg',
          'animation.frame_format': 'png',
          'animation.html': 'none',
          'animation.writer': 'ffmpeg',
          'axes.autolimit_mode': 'data',
          'axes.axisbelow': 'line',
          'axes.edgecolor': 'black',
          'axes.facecolor': 'white',
          'axes.formatter.limits': [-5, 6],
          'axes.formatter.min_exponent': 0,
          'axes.formatter.offset_threshold': 4,
          'axes.formatter.use_locale': False,
          'axes.formatter.use_mathtext': False,
          'axes.formatter.useoffset': True,
          'axes.grid': False,
          'axes.grid.axis': 'both',
   

In [135]:
df = pd.read_csv("C:\\Users\\aditi\\Downloads\\DA,DS\\UG PROJECT\\MODEL\\dams_lifetime.csv")
df.head()

Country Type     H  constuction_year  failure_year  Age 
0  Algeria   pg  42.0            1884.0          1885   2.0
1  Algeria   pg  43.0            1871.0          1881   4.0
2  Algeria   pg  43.0            1885.0          1927   4.0
3  Algeria   pg   2.0            1858.0          1885   4.0
4  Algeria   te  27.0            1861.0          1862   3.0

In [136]:
df.shape

(169, 6)

DATA CLEANING

In [137]:
df.groupby('Country')['Country'].agg('count')

Country
Algeria            5
Argentina          1
Australia          2
Brazil             7
Canada             3
Chile              4
China              3
Czechoslovakia     1
France             2
Great Britain      5
India             22
Italy              2
Japan              4
Korea              1
Leshoto            1
Lybya              1
Mexico             1
New Zealand        1
Nigeria            1
Pakistan           1
Romania            1
South Africa       8
Spain              6
Sri Lanka          1
Sweden             2
Turkey             1
USA               78
USSR               2
Yugoslavia         2
Name: Country, dtype: int64

In [138]:
df1 = df.drop('Type', axis='columns')
df1.head()

Country     H  constuction_year  failure_year  Age 
0  Algeria  42.0            1884.0          1885   2.0
1  Algeria  43.0            1871.0          1881   4.0
2  Algeria  43.0            1885.0          1927   4.0
3  Algeria   2.0            1858.0          1885   4.0
4  Algeria  27.0            1861.0          1862   3.0

In [139]:
df1.isnull().sum()

Country             0
H                   5
constuction_year    7
failure_year        0
Age                 3
dtype: int64

In [140]:
df1.H = df1.H.fillna(df1.H.mean())
df1.H.isnull().sum()

0

In [141]:
df2 = df1.dropna()
df2.isnull().sum()

Country             0
H                   0
constuction_year    0
failure_year        0
Age                 0
dtype: int64

In [142]:
df2['Age '].unique()

array([2., 4., 3., 1.])

In [143]:
df2.head()


Country     H  constuction_year  failure_year  Age 
0  Algeria  42.0            1884.0          1885   2.0
1  Algeria  43.0            1871.0          1881   4.0
2  Algeria  43.0            1885.0          1927   4.0
3  Algeria   2.0            1858.0          1885   4.0
4  Algeria  27.0            1861.0          1862   3.0

MACHINE LEARNING

In [144]:
dummies = pd.get_dummies(df2.Country)
dummies = dummies.astype(int)
dummies

Algeria  Argentina  Australia  Brazil  Canada  Chile  China  \
0          1          0          0       0       0      0      0   
1          1          0          0       0       0      0      0   
2          1          0          0       0       0      0      0   
3          1          0          0       0       0      0      0   
4          1          0          0       0       0      0      0   
..       ...        ...        ...     ...     ...    ...    ...   
164        0          0          0       0       0      0      0   
165        0          0          0       0       0      0      0   
166        0          0          0       0       0      0      0   
167        0          0          0       0       0      0      0   
168        0          0          0       0       0      0      0   

     Czechoslovakia  France  Great Britain  ...  Pakistan  Romania  \
0                 0       0              0  ...         0        0   
1                 0       0              0  ...         0        0   
2                 0       0              0  ...         0        0   
3                 0       0              0  ...         0        0   
4                 0       0              0  ...         0        0   
..              ...     ...            ...  ...       ...      ...   
164               0       0              0  ...         0        0   
165               0       0              0  ...         0        0   
166               0       0              0  ...         0        0   
167               0       0              0  ...         0        0   
168               0       0              0  ...         0        0   

     South Africa  Spain  Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0               0      0          0       0       0    0     0           0  
1               0      0          0       0       0    0     0           0  
2               0      0          0       0       0    0     0           0  
3               0      0          0       0       0    0     0           0  
4               0      0          0       0       0    0     0           0  
..            ...    ...        ...     ...     ...  ...   ...         ...  
164             0      0          0       0       0    1     0           0  
165             0      0          0       0       0    0     1           0  
166             0      0          0       0       0    0     1           0  
167             0      0          0       0       0    0     0           1  
168             0      0          0       0       0    0     0           1  

[161 rows x 29 columns]

In [145]:
df3 = pd.concat([df2, dummies], axis='columns')
df3.head()

Country     H  constuction_year  failure_year  Age   Algeria  Argentina  \
0  Algeria  42.0            1884.0          1885   2.0        1          0   
1  Algeria  43.0            1871.0          1881   4.0        1          0   
2  Algeria  43.0            1885.0          1927   4.0        1          0   
3  Algeria   2.0            1858.0          1885   4.0        1          0   
4  Algeria  27.0            1861.0          1862   3.0        1          0   

   Australia  Brazil  Canada  ...  Pakistan  Romania  South Africa  Spain  \
0          0       0       0  ...         0        0             0      0   
1          0       0       0  ...         0        0             0      0   
2          0       0       0  ...         0        0             0      0   
3          0       0       0  ...         0        0             0      0   
4          0       0       0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 34 columns]

In [146]:
df4 = df3.drop('Country', axis='columns')
df4.head()

H  constuction_year  failure_year  Age   Algeria  Argentina  Australia  \
0  42.0            1884.0          1885   2.0        1          0          0   
1  43.0            1871.0          1881   4.0        1          0          0   
2  43.0            1885.0          1927   4.0        1          0          0   
3   2.0            1858.0          1885   4.0        1          0          0   
4  27.0            1861.0          1862   3.0        1          0          0   

   Brazil  Canada  Chile  ...  Pakistan  Romania  South Africa  Spain  \
0       0       0      0  ...         0        0             0      0   
1       0       0      0  ...         0        0             0      0   
2       0       0      0  ...         0        0             0      0   
3       0       0      0  ...         0        0             0      0   
4       0       0      0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 33 columns]

In [147]:
df4.shape

(161, 33)

In [149]:
x = df4.drop(['failure_year','Age '], axis='columns')
y1 = df4[['failure_year']]
y2 = df4[['Age ']]

In [150]:
x.head()

H  constuction_year  Algeria  Argentina  Australia  Brazil  Canada  \
0  42.0            1884.0        1          0          0       0       0   
1  43.0            1871.0        1          0          0       0       0   
2  43.0            1885.0        1          0          0       0       0   
3   2.0            1858.0        1          0          0       0       0   
4  27.0            1861.0        1          0          0       0       0   

   Chile  China  Czechoslovakia  ...  Pakistan  Romania  South Africa  Spain  \
0      0      0               0  ...         0        0             0      0   
1      0      0               0  ...         0        0             0      0   
2      0      0               0  ...         0        0             0      0   
3      0      0               0  ...         0        0             0      0   
4      0      0               0  ...         0        0             0      0   

   Sri Lanka  Sweden  Turkey  USA  USSR  Yugoslavia  
0          0       0       0    0     0           0  
1          0       0       0    0     0           0  
2          0       0       0    0     0           0  
3          0       0       0    0     0           0  
4          0       0       0    0     0           0  

[5 rows x 31 columns]

In [151]:
y1.head()

failure_year
0          1885
1          1881
2          1927
3          1885
4          1862

In [ ]:
y2.head()

Age 
0   2.0
1   4.0
2   4.0
3   4.0
4   3.0

In [152]:
y = pd.concat([y1, y2], axis=1)

In [153]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split


In [154]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=42)

In [155]:
regressor = MultiOutputRegressor(RandomForestRegressor(random_state=42))

In [156]:
regressor.fit(x_train, y_train)

MultiOutputRegressor(estimator=RandomForestRegressor(random_state=42))

In [157]:
y_pred = regressor.predict(x_test)

In [158]:
y_pred_failure_year = y_pred[:,0]
y_pred_age = y_pred[:, 1]

In [159]:
y_pred_failure_year

array([1910.99      , 1901.942     , 1962.24      , 1978.4       ,
       1924.52      , 1945.14      , 1973.07      , 1961.1       ,
       1918.09      , 1957.14      , 1921.3925    , 1984.33      ,
       1917.53      , 1907.28083333, 1963.01      , 1972.59      ,
       1933.25      , 1880.85      , 1918.12      , 1955.87      ,
       1855.63      , 1917.59      , 1939.57      , 1975.75      ,
       1921.25      , 1970.19      , 1961.41      , 1980.94      ,
       1974.6       , 1907.65766667, 1916.3125    , 1972.84      ,
       1932.13      , 1965.59      , 1901.592     , 1977.93      ,
       1912.17      , 1855.81      , 1949.02      , 1950.23      ,
       1899.85933333, 1916.3125    ])

In [160]:
y_pred_age

array([2.455     , 3.713     , 2.34      , 2.56      , 2.62      ,
       2.96      , 2.96      , 3.13      , 3.713     , 3.19      ,
       3.168     , 3.09      , 3.19      , 3.26      , 3.28      ,
       3.3       , 3.12      , 3.33      , 2.85      , 3.515     ,
       3.61      , 3.24      , 2.9       , 1.98      , 3.48      ,
       1.87      , 2.3       , 2.37      , 2.68      , 3.68966667,
       3.28233333, 3.5       , 2.51      , 3.59      , 3.36033333,
       3.3       , 3.04      , 3.44      , 3.77      , 3.07      ,
       3.53633333, 3.28233333])

In [161]:
print("Predicted 'failure_year' values:")
print(y_pred_failure_year)
print("\nPredicted 'Age ' values:")
print(y_pred_age)

Predicted 'failure_year' values:
[1910.99       1901.942      1962.24       1978.4        1924.52
 1945.14       1973.07       1961.1        1918.09       1957.14
 1921.3925     1984.33       1917.53       1907.28083333 1963.01
 1972.59       1933.25       1880.85       1918.12       1955.87
 1855.63       1917.59       1939.57       1975.75       1921.25
 1970.19       1961.41       1980.94       1974.6        1907.65766667
 1916.3125     1972.84       1932.13       1965.59       1901.592
 1977.93       1912.17       1855.81       1949.02       1950.23
 1899.85933333 1916.3125    ]

Predicted 'Age ' values:
[2.455      3.713      2.34       2.56       2.62       2.96
 2.96       3.13       3.713      3.19       3.168      3.09
 3.19       3.26       3.28       3.3        3.12       3.33
 2.85       3.515      3.61       3.24       2.9        1.98
 3.48       1.87       2.3        2.37       2.68       3.68966667
 3.28233333 3.5        2.51       3.59       3.36033333 3.3
 3.04       3

In [ ]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(x_train, y_train)
lr_clf.score(x_test, y_test)

-0.16821316790122753

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

cross_val_score(LinearRegression(), x, y, cv=cv)

array([ 9.85535458e-02,  1.22846606e-01,  1.67368119e-02, -2.35871504e+20,
       -3.49607588e-01])

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchCV(x,y):
    algos = {
        'linear_regression': {
            'model' : LinearRegression(),
            'params' :{
                'positive' : [True, False]
            }
        },
        'lasso' :{
            'model' : Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random','cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion': ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
         }
    }

    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs = GridSearchCV(config['model'],config['params'], cv=cv, return_train_score=False)
        gs.fit(x,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
    })
    
    return pd.DataFrame(scores,columns=['model','best_score', 'best_params'])

find_best_model_using_gridsearchCV(x,y)

C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
10 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py", line 638, in _validate_params
    validate_pa

model    best_score  \
0  linear_regression -4.717430e+19   
1              lasso  1.698768e-01   
2      decision_tree -4.959266e-01   

                                         best_params  
0                                {'positive': False}  
1                {'alpha': 2, 'selection': 'random'}  
2  {'criterion': 'friedman_mse', 'splitter': 'best'}

In [162]:
def predict(Country,H	,constuction_year):
    Con_index = np.where(x.columns==Country)[0][0]
    x_input = np.zeros(len(x.columns))
    x_input[0] = H
    x_input[1] = constuction_year

    if Con_index >=0:
        x_input[Con_index] = 1
    return lr_clf.predict([x_input])[0]

In [164]:
predict('India',43,1945)

C:\Users\aditi\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1953.08555526,    2.50396188])

MODEL EXPORTING

In [165]:
import pickle
with open('dam_failure_model.pickle', 'wb') as f:
    pickle.dump(lr_clf,f)

In [166]:
import json
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open ('columns.json', 'w') as f:
    f.write(json.dumps(columns))